### ISSUE TITLE
Optional event parameters are marked as required in the generated SDK

### ISSUE THREAD

**Issue by mptorz** [iterativelyhq/itly-sdk#46]
Hey, 

I see this is the first issue created, so just wanted to say that we really love your product 👍🏻 

I am having a small issue though. I created an event with some optional properties, but when SDK is generated they are typed as required, so typescript throws error when I pass undefined.

I pulled the latest tracking plan and you can see the type of the property is not required:
<img width="404" alt="Screenshot 2021-03-05 at 15 27 46" src="https://user-images.githubusercontent.com/20892770/110130476-56050480-7dc9-11eb-9a25-43583f5afe83.png">

But then in the code it is typed as a `string` NOT as a `string | undefined`
<img width="337" alt="Screenshot 2021-03-05 at 15 42 54" src="https://user-images.githubusercontent.com/20892770/110130577-746b0000-7dc9-11eb-813e-86ccb2bb22d5.png">

This is really confusing. Am I doing something wrong?

**Comment by justin-iteratively** [comment]
Hi @mptorz thanks for the kind words. I'm glad you are enjoying the product. 

I believe the issue that you are seeing is due to a bug with the JSDocs in the generated tracking library.  We have fixed this issue and have it included in our next major release which is targeted for early next week.

In the meantime there are a couple of workarounds.
1. This bug only exists in the "Browser/Javascript" runtime. If you are using Typescript you could change your runtime to "Browser/Typescript" instead and re-run `itly pull` to get the new TS tracking library sans errors and with strong types.  
2. The error is caused by the JSDocs in the the generated `./src/itly/index.js`. You can (temporarily) fix it by modifying the JSDoc to correctly [mark the property as optional by enclosing the property name in brackets](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values). Note that each time you run `itly pull` this file will be overwritten and you will lose your edits.
```
  /**
   * Event w optional properties description
   * 
   * Owner: Test codegen
   * @param {Object} properties The event's properties.
   * ...
   * @param {string} [properties.medicine] Name of the medicine
   */
  sessionCanceled(properties) { ... }
```

I will provide an update when we release the next version of the SDK with the fix.

If you would like early access to the new SDK please contact me directly and I can enable it on you account.

Best,
Justin
justin@iterative.ly

**Comment by mptorz** [comment]
Hey, thanks a lot for a quick resolution :)

Someone else was setting up our tracking plan and I missed the fact that the runtime was set to `Javascript` instead of `Typescript`. Everything works fine after we changed it to Typescript 👍🏻
